apiVersion: v1
kind: LimitRange
metadata:
 name: demo-limit-range
spec:
 limits:
 # will apply if the container doesn't specify the container limits
   - default:
       cpu: 500m
       memory: 512Mi
     defaultRequest:
       cpu: 100m
       memory: 256Mi
     max:
       cpu: 1 # 1 core of cpu
       memory: 1Gi
     min:
       cpu: 50m
       memory: 128Mi
     type: Container