apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpass-secret"}},"mappingMethod":"claim","name":"developer","type":"HTPasswd"}],"tokenConfig":{"accessTokenMaxAgeSeconds":31536000}}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-07-10T09:36:58Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 78aeee1c-4985-449b-8949-a083af2417f6
  resourceVersion: "18658"
  uid: 362a82ae-b303-457a-8266-80ce1eba6814
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: developer
    type: HTPasswd
  tokenConfig:
    accessTokenMaxAgeSeconds: 31536000
